export const ICON_REPLACE_ROUTE = "ICON_REPLACE_ROUTE";
export const ICON_PUSH_NEW_ROUTE = "ICON_PUSH_NEW_ROUTE";
export const ICON_POP_ROUTE = "ICON_POP_ROUTE";
export const ICON_POP_TO_ROUTE = "ICON_POP_TO_ROUTE";
//Login
export const MA_LOGIN_REQUEST = "MA_LOGIN_REQUEST";
export const MA_LOGIN_SUCCESS = "MA_LOGIN_SUCCESS";
export const MA_LOGIN_FAILED = "MA_LOGIN_FAILED";

//SignUp
export const ICON_SIGNUP_REQUEST = "ICON_SIGNUP_REQUEST";
export const ICON_SIGNUP_SUCCESS = "ICON_SIGNUP_SUCCESS";
export const ICON_SIGNUP_FAILED = "ICON_SIGNUP_FAILED";

//SignUpActivation Code
export const ICON_SIGNUP_ACTCODE_REQUEST = "ICON_SIGNUP_ACTCODE_REQUEST";
export const ICON_SIGNUP_ACTCODE_SUCCESS = "ICON_SIGNUP_ACTCODE_SUCCESS";
export const ICON_SIGNUP_ACTCODE_FAILED = "ICON_SIGNUP_ACTCODE_FAILED";

export const ICON_SIGNUP_ACTVALIDATE_REQUEST =
  "ICON_SIGNUP_ACTVALIDATE_REQUEST";
export const ICON_SIGNUP_ACTVALIDATE_SUCCESS =
  "ICON_SIGNUP_ACTVALIDATE_SUCCESS";
export const ICON_SIGNUP_ACTVALIDATE_FAILED = "ICON_SIGNUP_ACTVALIDATE_FAILED";

//Privacy policy
export const ICON_PRIVACYPOLICY_REQUEST = "ICON_PRIVACYPOLICY_REQUEST";
export const ICON_PRIVACYPOLICY_SUCCESS = "ICON_PRIVACYPOLICY_SUCCESS";
export const ICON_PRIVACYPOLICY_FAILED = "ICON_PRIVACYPOLICY_FAILED";

//Wishlist
export const ICON_WISHLIST_REQUEST = "ICON_WISHLIST_REQUEST";
export const ICON_WISHLIST_SUCCESS = "ICON_WISHLIST_SUCCESS";
export const ICON_WISHLIST_FAILED = "ICON_WISHLIST_FAILED";

export const ICON_UPDATE_WISHLIST_REQUEST = "ICON_UPDATE_WISHLIST_REQUEST";
export const ICON_UPDATE_WISHLIST_SUCCESS = "ICON_UPDATE_WISHLIST_SUCCESS";
export const ICON_UPDATE_WISHLIST_FAILED = "ICON_UPDATE_WISHLIST_FAILED";

export const ICON_DEL_WISHLIST_REQUEST = "ICON_DEL_WISHLIST_REQUEST";
export const ICON_DEL_WISHLIST_SUCCESS = "ICON_DEL_WISHLIST_SUCCESS";
export const ICON_DEL_WISHLIST_FAILED = "ICON_DEL_WISHLIST_FAILED";

export const ICON_GETBOOKS_REQUEST = "ICON_GETBOOKS_REQUEST";
export const ICON_GETBOOKS_SUCCESS = "ICON_GETBOOKS_SUCCESS";
export const ICON_GETBOOKS_FAILED = "ICON_GETBOOKS_FAILED";

export const ICON_GETCAMPUSDETAILS_FAILED = "ICON_GETCAMPUSDETAILS_FAILED";
export const ICON_GETCAMPUSDETAILS_REQUEST = "ICON_GETCAMPUSDETAILS_REQUEST";
export const ICON_GETCAMPUSDETAILS_SUCCESS = "ICON_GETCAMPUSDETAILS_SUCCESS";

//ChangePwd
export const ICON_CHANGEPWD_REQUEST = "ICON_CHANGEPWD_REQUEST";
export const ICON_CHANGEPWD_SUCCESS = "ICON_CHANGEPWD_SUCCESS";
export const ICON_CHANGEPWD_FAILED = "ICON_CHANGEPWD_FAILED";

//ForgotPwd
export const ICON_FORGOTPWD_REQUEST = "ICON_FORGOTPWD_REQUEST";
export const ICON_FORGOTPWD_SUCCESS = "ICON_FORGOTPWD_SUCCESS";
export const ICON_FORGOTPWD_FAILED = "ICON_FORGOTPWD_FAILED";

export const ICON_FORGOTPWDCODE_REQUEST = "ICON_FORGOTPWDCODE_REQUEST";
export const ICON_FORGOTPWDCODE_SUCCESS = "ICON_FORGOTPWDCODE_SUCCESS";
export const ICON_FORGOTPWDCODE_FAILED = "ICON_FORGOTPWDCODE_FAILED";

export const ICON_FORGOTPWDSETNEW_REQUEST = "ICON_FORGOTPWDSETNEW_REQUEST";
export const ICON_FORGOTPWDSETNEW_SUCCESS = "ICON_FORGOTPWDSETNEW_SUCCESS";
export const ICON_FORGOTPWDSETNEW_FAILED = "ICON_FORGOTPWDSETNEW_FAILED";

//Create Feeds
export const ICON_CREATEFEED_REQUEST = "ICON_CREATEFEED_REQUEST";
export const ICON_CREATEFEED_SUCCESS = "ICON_CREATEFEED_SUCCESS";
export const ICON_CREATEFEED_FAILED = "ICON_CREATEFEED_FAILED";

//GET Feeds Category
export const ICON_GETFEEDCATEGORY_REQUEST = "ICON_GETFEEDCATEGORY_REQUEST";
export const ICON_GETFEEDCATEGORY_SUCCESS = "ICON_GETFEEDCATEGORY_SUCCESS";
export const ICON_GETFEEDCATEGORY_FAILED = "ICON_GETFEEDCATEGORY_FAILED";

export const ON_CAMPUS_LISTING_RECEIVED = "ON_CAMPUS_LISTING_RECEIVED";
export const GET_LISTING_BY_CAMPUS_FAILED = "GET_LISTING_BY_CAMPUS_FAILED";
export const GET_MY_LISTING_REQUEST_FAILED = "GET_MY_LISTING_REQUEST_FAILED";
export const ON_BOOKS_SEARCH_TEXT = "ON_BOOKS_SEARCH_TEXT";
export const ON_MY_LISTING_RECEIVED = "ON_MY_LISTING_RECEIVED";
export const RESET_MY_LISTING = "RESET_MY_LISTING";
export const ON_LISTING_DELISTED = "ON_LISTING_DELISTED";
export const ON_LISTING_MARK_AS_SOLD = "ON_LISTING_MARK_AS_SOLD";
export const ON_LISTING_DELETED = "ON_LISTING_DELETED";
export const ON_BOOKS_UNMOUNTED = "ON_BOOKS_UNMOUNTED";
export const ON_LISTING_ACTIVATED = "ON_LISTING_ACTIVATED";
export const ON_MARKED_VIEW_SUCCESS = "ON_MARKED_VIEW_SUCCESS";
export const ON_MARKED_VIEW_FAILED = "ON_MARKED_VIEW_FAILED";
export const ON_MARKED_FAVOURITE_SUCCESS = "ON_MARKED_FAVOURITE_SUCCESS";
export const ON_MARKED_FAVOURITE_FAILED = "ON_MARKED_FAVOURITE_FAILED";
export const ON_MARKED_UNFAVOURITE_SUCCESS = "ON_MARKED_UNFAVOURITE_SUCCESS";
export const ON_MARKED_UNFAVOURITE_FAILED = "ON_MARKED_UNFAVOURITE_FAILED";
export const ON_LISTING_ACTIVATE_FAILED = "ON_LISTING_ACTIVATE_FAILED";
export const ON_MARK_AS_SOLD_FAILED = "ON_MARK_AS_SOLD_FAILED";
export const ON_BOOK_DELISTED_FAILED = "ON_BOOK_DELISTED_FAILED";
export const ON_LISTING_DELETED_FAILED = "ON_LISTING_DELETED_FAILED";
export const ON_MY_FAVORITES_RECEIVED = "ON_MY_FAVORITES_RECEIVED";
export const GET_MY_FAVORITES_REQUEST_FAILED =
  "GET_MY_FAVORITES_REQUEST_FAILED";
export const ON_CAMPUS_FURNITURE_LISTING_RECEIVED =
  "ON_CAMPUS_FURNITURE_LISTING_RECEIVED";
export const GET_FURNITURE_LISTING_BY_CAMPUS_FAILED =
  "GET_FURNITURE_LISTING_BY_CAMPUS_FAILED";
export const ON_FURNITURE_FILTER_APPLY = "ON_FURNITURE_FILTER_APPLY";
export const ON_CAMPUS_MISCELLANEOUS_LISTING_RECEIVED =
  "ON_CAMPUS_MISCELLANEOUS_LISTING_RECEIVED";
export const GET_MISCELLANEOUS_LISTING_BY_CAMPUS_FAILED =
  "GET_MISCELLANEOUS_LISTING_BY_CAMPUS_FAILED";
export const ON_MISCELLANEOUS_FILTER_APPLY = "ON_MISCELLANEOUS_FILTER_APPLY";
export const NEW_BOOK_ADDED = "NEW_BOOK_ADDED";
export const BOOK_LISTING_UPDATED = "BOOK_LISTING_UPDATED";
export const NEW_FURNITURE_ADDED = "NEW_FURNITURE_ADDED";
export const FURNITURE_UPDATED = "FURNITURE_UPDATED";
export const NEW_MISCELLANEOUS_ADDED = "NEW_MISCELLANEOUS_ADDED";
export const MISCELLANEOUS_UPDATED = "MISCELLANEOUS_UPDATED";

export const NEW_LOOKING_FOR_APARTMENT_ADDED =
  "NEW_LOOKING_FOR_APARTMENT_ADDED";
export const LOOKING_FOR_APARTMENT_UPDATED = "LOOKING_FOR_APARTMENT_UPDATED";
export const ON_CAMPUS_APARTMENT_LISTING_RECEIVED =
  "ON_CAMPUS_APARTMENT_LISTING_RECEIVED";
export const ON_GET_CAMPUS_APARTMENT_LISTING_FAILED =
  "ON_GET_CAMPUS_APARTMENT_LISTING_FAILED";
export const NEW_LOOKING_ROOMMATE_ADDED = "NEW_LOOKING_ROOMMATE_ADDED";
export const LOOKING_FOR_ROOMMATE_UPDATED = "LOOKING_FOR_ROOMMATE_UPDATED";
export const ON_CAMPUS_ROOMMATES_LISTING_RECEIVED =
  "ON_CAMPUS_ROOMMATES_LISTING_RECEIVED";
export const ON_GET_CAMPUS_ROOMMATES_LISTING_FAILED =
  "ON_GET_CAMPUS_ROOMMATES_LISTING_FAILED";

export const ICON_GETFEEDS_FAILED = "ICON_GETFEEDS_FAILED";
export const ICON_GETFEEDS_SUCCESS = "ICON_GETFEEDS_SUCCESS";

export const ICON_GETMYFEEDS_FAILED = "ICON_GETMYFEEDS_FAILED";
export const ICON_GETMYFEEDS_SUCCESS = "ICON_GETMYFEEDS_SUCCESS";

export const ICON_ADDCOMMENTSTOFEEDS_FAILED = "ICON_ADDCOMMENTSTOFEEDS_FAILED";
export const ICON_ADDCOMMENTSTOFEEDS_SUCCESS =
  "ICON_ADDCOMMENTSTOFEEDS_SUCCESS";
export const BOOK_REF_DATA_RECEIVED = "BOOK_REF_DATA_RECEIVED";
export const FURNITURE_REF_DATA_RECEIVED = "FURNITURE_REF_DATA_RECEIVED";
export const MISCELLANEOUS_REF_DATA_RECEIVED =
  "MISCELLANEOUS_REF_DATA_RECEIVED";
export const APARTEMENT_REF_DATA_RECEIVED = "APARTEMENT_REF_DATA_RECEIVED";
export const ROOMMATE_REF_DATA_RECEIVED = "ROOMMATE_REF_DATA_RECEIVED";
export const ON_ROOMMATE_FILTER_SELECTED = "ON_ROOMMATE_FILTER_SELECTED";

export const ICON_GETCOMMENTS_FAILED = "ICON_GETCOMMENTS_FAILED";
export const ICON_GETCOMMENTS_SUCCESS = "ICON_GETCOMMENTS_SUCCESS";
export const ICON_ADDREACTIONTOFEED_FAILED = "ICON_ADDREACTIONTOFEED_FAILED";
export const ICON_ADDREACTIONTOFEED_SUCCESS = "ICON_ADDREACTIONTOFEED_SUCCESS";

export const ICON_ADDREACTIONTOCOMMENTS_FAILED =
  "ICON_ADDREACTIONTOCOMMENTS_FAILED";
export const ICON_ADDREACTIONTOCOMMENTS_SUCCESS =
  "ICON_ADDREACTIONTOCOMMENTS_SUCCESS";
